<?php
/**
 * TL_ROOT/system/modules/vcard/languages/de/default.php 
 * 
 * Contao extension: vcard 1.1.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['vcard']['0'] = "vCard";
$GLOBALS['TL_LANG']['CTE']['vcard']['1'] = "Dieses Element enthält einen Verweis auf eine Visitenkarte (vCard), die von Besuchern der Webseite heruntergeladen werden kann.";
 
?>
