<?php
/**
 * TL_ROOT/system/modules/vcard/languages/de/tl_content.php 
 * 
 * Contao extension: vcard 1.1.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['vcard_type']['0'] = "Anzeigen für";
$GLOBALS['TL_LANG']['tl_content']['vcard_type']['1'] = "Bitte wählen Sie aus, für welche Personengruppe eine Visitenkarte angezeigt werden soll.";
$GLOBALS['TL_LANG']['tl_content']['vcard_type']['vmember'] = "Mitglieder";
$GLOBALS['TL_LANG']['tl_content']['vcard_type']['vhttp'] = "HTTP Parameter";
$GLOBALS['TL_LANG']['tl_content']['vcard_type']['vcustom'] = "Individuelle Angabe";
$GLOBALS['TL_LANG']['tl_content']['vcard_member']['0'] = "Mitglied";
$GLOBALS['TL_LANG']['tl_content']['vcard_member']['1'] = "Bitte wählen Sie ein Frontend-Mitglied aus, für das die Visitenkarte angezeigt werden soll.";
$GLOBALS['TL_LANG']['tl_content']['vcard_http']['0'] = "HTTP Parameter";
$GLOBALS['TL_LANG']['tl_content']['vcard_http']['1'] = "Bitte geben Sie einen HTTP GET oder HTTP POST Parameter an, aus dem die ID des Mitglieds ermittelt werden soll. Ist der Parameter während der Laufzeit dieses Inhaltselements gesetzt, ermittelt TYPOlight die ID des gewünschten Mitglieds.";
$GLOBALS['TL_LANG']['tl_content']['vcard_title'] = "Visitenkarte herunterladen";
$GLOBALS['TL_LANG']['tl_content']['vc_title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_content']['vc_title']['1'] = "Bitte geben Sie den Titel ein.";
$GLOBALS['TL_LANG']['tl_content']['vc_firstname']['0'] = "Vorname";
$GLOBALS['TL_LANG']['tl_content']['vc_firstname']['1'] = "Bitte geben Sie den Vornamen ein.";
$GLOBALS['TL_LANG']['tl_content']['vc_lastname']['0'] = "Nachname";
$GLOBALS['TL_LANG']['tl_content']['vc_lastname']['1'] = "Bitte geben Sie den Nachnamen ein.";
$GLOBALS['TL_LANG']['tl_content']['vc_birthday']['0'] = "Geburtsdatum";
$GLOBALS['TL_LANG']['tl_content']['vc_birthday']['1'] = "Bitte geben Sie das Geburtsdatum ein.";
$GLOBALS['TL_LANG']['tl_content']['vc_company']['0'] = "Firma";
$GLOBALS['TL_LANG']['tl_content']['vc_company']['1'] = "Hier können Sie einen Firmennamen eintragen.";
$GLOBALS['TL_LANG']['tl_content']['vc_department']['0'] = "Abteilung";
$GLOBALS['TL_LANG']['tl_content']['vc_department']['1'] = "Hier können Sie den Namen einer Abteilung eintragen.";
$GLOBALS['TL_LANG']['tl_content']['vc_jobtitle']['0'] = "Berufsbezeichnung";
$GLOBALS['TL_LANG']['tl_content']['vc_jobtitle']['1'] = "Hier können Sie eine Berufsbezeichnung eintragen.";
$GLOBALS['TL_LANG']['tl_content']['vc_box_work']['0'] = "Postfach";
$GLOBALS['TL_LANG']['tl_content']['vc_box_work']['1'] = "Bitte geben Sie das Postfach ein.";
$GLOBALS['TL_LANG']['tl_content']['vc_street_work']['0'] = "Straße";
$GLOBALS['TL_LANG']['tl_content']['vc_street_work']['1'] = "Bitte geben Sie den Straßennamen und die Hausnummer ein.";
$GLOBALS['TL_LANG']['tl_content']['vc_postal_work']['0'] = "Postleitzahl";
$GLOBALS['TL_LANG']['tl_content']['vc_postal_work']['1'] = "Bitte geben Sie die Postleitzahl ein.";
$GLOBALS['TL_LANG']['tl_content']['vc_city_work']['0'] = "Stadt";
$GLOBALS['TL_LANG']['tl_content']['vc_city_work']['1'] = "Bitte geben Sie die Stadt ein.";
$GLOBALS['TL_LANG']['tl_content']['vc_state_work']['0'] = "Staat";
$GLOBALS['TL_LANG']['tl_content']['vc_state_work']['1'] = "Bitte geben Sie den Namen des Staates ein.";
$GLOBALS['TL_LANG']['tl_content']['vc_country_work']['0'] = "Land";
$GLOBALS['TL_LANG']['tl_content']['vc_country_work']['1'] = "Bitte wählen Sie ein Land.";
$GLOBALS['TL_LANG']['tl_content']['vc_street_home']['0'] = "Straße";
$GLOBALS['TL_LANG']['tl_content']['vc_street_home']['1'] = "Bitte geben Sie den Straßennamen und die Hausnummer ein.";
$GLOBALS['TL_LANG']['tl_content']['vc_box_home']['0'] = "Postfach";
$GLOBALS['TL_LANG']['tl_content']['vc_box_home']['1'] = "Bitte geben Sie das Postfach ein.";
$GLOBALS['TL_LANG']['tl_content']['vc_postal_home']['0'] = "Postleitzahl";
$GLOBALS['TL_LANG']['tl_content']['vc_postal_home']['1'] = "Bitte geben Sie die Postleitzahl ein.";
$GLOBALS['TL_LANG']['tl_content']['vc_city_home']['0'] = "Stadt";
$GLOBALS['TL_LANG']['tl_content']['vc_city_home']['1'] = "Bitte geben Sie die Stadt ein.";
$GLOBALS['TL_LANG']['tl_content']['vc_state_home']['0'] = "Staat";
$GLOBALS['TL_LANG']['tl_content']['vc_state_home']['1'] = "Bitte geben Sie den Namen des Staates ein.";
$GLOBALS['TL_LANG']['tl_content']['vc_country_home']['0'] = "Land";
$GLOBALS['TL_LANG']['tl_content']['vc_country_home']['1'] = "Bitte wählen Sie ein Land.";
$GLOBALS['TL_LANG']['tl_content']['vc_phone_work']['0'] = "Telefonnummer (Arbeit)";
$GLOBALS['TL_LANG']['tl_content']['vc_phone_work']['1'] = "Bitte geben Sie die Telefonnummer ein.";
$GLOBALS['TL_LANG']['tl_content']['vc_fax_work']['0'] = "Faxnummer (Arbeit)";
$GLOBALS['TL_LANG']['tl_content']['vc_fax_work']['1'] = "Bitte geben Sie die Faxnummer ein.";
$GLOBALS['TL_LANG']['tl_content']['vc_phone_mobile']['0'] = "Mobilfunknummer";
$GLOBALS['TL_LANG']['tl_content']['vc_phone_mobile']['1'] = "Bitte geben Sie die Mobilfunknummer ein.";
$GLOBALS['TL_LANG']['tl_content']['vc_phone_home']['0'] = "Telefonnummer (Privat)";
$GLOBALS['TL_LANG']['tl_content']['vc_phone_home']['1'] = "Bitte geben Sie die Telefonnummer ein.";
$GLOBALS['TL_LANG']['tl_content']['vc_mail1']['0'] = "E-Mail-Adresse 1";
$GLOBALS['TL_LANG']['tl_content']['vc_mail1']['1'] = "Bitte geben Sie eine gültige E-Mail-Adresse ein.";
$GLOBALS['TL_LANG']['tl_content']['vc_mail2']['0'] = "E-Mail-Adresse 2";
$GLOBALS['TL_LANG']['tl_content']['vc_mail2']['1'] = "Bitte geben Sie eine gültige E-Mail-Adresse ein.";
$GLOBALS['TL_LANG']['tl_content']['vc_mail3']['0'] = "E-Mail-Adresse 3";
$GLOBALS['TL_LANG']['tl_content']['vc_mail3']['1'] = "Bitte geben Sie eine gültige E-Mail-Adresse ein.";
$GLOBALS['TL_LANG']['tl_content']['vc_web']['0'] = "Website";
$GLOBALS['TL_LANG']['tl_content']['vc_web']['1'] = "Hier können Sie eine Web-Adresse eingeben.";
$GLOBALS['TL_LANG']['tl_content']['vc_encoding']['0'] = "vCard-Kodierung";
$GLOBALS['TL_LANG']['tl_content']['vc_encoding']['1'] = "Legen Sie die Kodierung der vCard fest. Der Standard ist UTF-8 (Unicode). Ältere Microsoft Outlook-Versionen benötigen jedoch Latin-1 Windows-Kodierung.";
$GLOBALS['TL_LANG']['tl_content']['encoding']['utf-8'] = "UTF-8 Kodierung (empfohlen)";
$GLOBALS['TL_LANG']['tl_content']['encoding']['latin1'] = "Latin-1 (Windows) Kodierung, z.B. für Microsoft Outlook";
$GLOBALS['TL_LANG']['tl_content']['encoding']['both'] = "Beide, UTF-8 Kodierung und Latin-1 (Windows) Kodierung";
$GLOBALS['TL_LANG']['tl_content']['vcardtype_legend'] = "Visitenkarten-Typ";
$GLOBALS['TL_LANG']['tl_content']['personal_legend'] = "Personendaten";
$GLOBALS['TL_LANG']['tl_content']['address_work_legend'] = "Adressdaten (Arbeit)";
$GLOBALS['TL_LANG']['tl_content']['address_home_legend'] = "Adressdaten (Privat)";
$GLOBALS['TL_LANG']['tl_content']['communication_legend'] = "Kontaktdaten";
 
?>
